version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: table_football_postgres
    restart: always
    environment:
      POSTGRES_USER: football_admin
      POSTGRES_PASSWORD: EvoconChamp
      POSTGRES_DB: table_football_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: